### PR TITLE
Darwin builds?

### PR DESCRIPTION
**Pull request by kanterov**
I see that you are not accepting code contributions. You can see it more as proposal or question.

I did a few tweaks to build files and the source code to build on Mac, and it seems to work. I'm wondering what you think about having Mac builds. I hope you (or somebody else) will find this patch useful.

### CODE REVIEW

**Comment by apilloud** [comment]
Hi Gleb! We are interested in supporting other platforms, so thanks for doing this! While we aren't ready to accept external patches yet we can keep this open as a feature request until we can.

**Comment by kanterov** [comment]
Updated and rebased on the latest master.

**Comment by kanterov** [comment]
Updated and rebased on the latest master. I had to hack source_location because my version of clang doesn't have necessary builtins.

**Comment by georgewfraser** [comment]
@kanterov I'm trying to build your branch, but I'm getting an error:

```
...lots of stuff...
checking the archiver (/usr/bin/libtool) interface... unknown
configure: error: could not determine /usr/bin/libtool interface
```

And ideas? I have the native toolchain you get when your run `xcode-select --install`

**Comment by kanterov** [comment]
@georgewfraser what Bazel version do you use? As @apilloud has mentioned, it only works with 0.25.3 to 0.29.1. From the error message, it looks like something is wrong with `ar`. Reverting these lines might help:

https://github.com/google/zetasql/pull/3/files#diff-15c0f819916ef1d2c8fe4824082c3309R41-R43

**Comment by georgewfraser** [comment]
@kanterov OK, now my problem is sed is not working: 

zetasql % USE_BAZEL_VERSION=0.25.3 bazelisk build --verbose_failures --sandbox_debug zetasql/parser:gen_extra_files
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Analyzed target //zetasql/parser:gen_extra_files (3 packages loaded, 20 targets configured).
INFO: Found 1 target...
ERROR: /Users/george/Documents/zetasql/zetasql/parser/BUILD:23:1: Executing genrule //zetasql/parser:gen_extra_files failed (Exit 1) sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_george/cdc7303f6251c90d9b54597ea1ddb99e/sandbox/darwin-sandbox/1/execroot/com_google_zetasql && \
  exec env - \
    PATH=/Users/george/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/george/google-cloud-sdk/bin:/Users/george/bin:/Users/george/go/bin:/Users/george/bin:/Users/george/go/bin \
    TMPDIR=/var/folders/m7/71lfbk7d157ffpsx374gslk00000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_george/cdc7303f6251c90d9b54597ea1ddb99e/sandbox/darwin-sandbox/1/sandbox.sb /var/tmp/_bazel_george/install/24e67df1a714df6e761fc8e136714812/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; zetasql/parser/gen_extra_files.sh zetasql/parser/parse_tree.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_visitor.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_decls.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_accept_methods.inc'): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_george/cdc7303f6251c90d9b54597ea1ddb99e/sandbox/darwin-sandbox/1/execroot/com_google_zetasql && \
  exec env - \
    PATH=/Users/george/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/george/google-cloud-sdk/bin:/Users/george/bin:/Users/george/go/bin:/Users/george/bin:/Users/george/go/bin \
    TMPDIR=/var/folders/m7/71lfbk7d157ffpsx374gslk00000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_george/cdc7303f6251c90d9b54597ea1ddb99e/sandbox/darwin-sandbox/1/sandbox.sb /var/tmp/_bazel_george/install/24e67df1a714df6e761fc8e136714812/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; zetasql/parser/gen_extra_files.sh zetasql/parser/parse_tree.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_visitor.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_decls.h bazel-out/darwin-fastbuild/bin/zetasql/parser/parse_tree_accept_methods.inc')
sed: -: No such file or directory
Target //zetasql/parser:gen_extra_files failed to build
INFO: Elapsed time: 11.973s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by kanterov** [comment]
@georgewfraser this script requires GNU sed, while Mac by default has BSD sed. You can install BSD sed with homebrew

**Comment by kanterov** [comment]
Fixed in https://github.com/google/zetasql/commit/fbb6fc6af8d4ad5f384a12730fe07423f51bfce0

**Pull request closed without merging**
